ci: add auto versioning

diff --git a/.github/workflows/build-pr.yaml b/.github/workflows/build-pr.yaml
--- a/.github/workflows/build-pr.yaml
+++ b/.github/workflows/build-pr.yaml
@@ -8,18 +8,58 @@ on:
 jobs:
   build:
     name: Build
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     defaults:
       run:
-        shell: powershell
+        shell: pwsh
     steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+
+
+      # Versioning
+      - name: Install .NET Core
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 6.x
+
+      - name: Versioning project's csproj file
+        run: |
+          # install prerequisites
+          sudo apt-get install -y xmlstarlet
+          
+          $cprojFiles = @(
+            "./GameDb/GameDb.csproj",
+            "./GameDb.Core/GameDb.Core.csproj",
+            "./GameDb.Models/GameDb.Models.csproj",
+          )
+
+          foreach($proj in $cprojFiles) {
+            $versionNo= & xmlstarlet  sel -t -m '/Project/PropertyGroup/AssemblyVersion' -v . < $proj
+          
+            # if fails to extract version number, then let workflow fail
+            Write-Host "Extracted version is: $versionNo"
+            if ($versionNo -ne $null) {
+              Write-Host "::error ::Failed to read version number from project file."
+              exit 1
+            }              
+            
+            # append build number if requested
+            if ($env:GITHUB_REF_NAME -ne "main") {
+              Write-Host "Appending build number to version"
+              $versionNo=$versionNo.$env:GITHUB_RUN_ID
+            }
+            Write-Host "Using version '$versionNo' for this build artifact"
+            Write-Host "artifact_version=$versionNo" >> $env:GITHUB_ENV  
+          }
+
+          
+      # Prepare SonarCloud
       - name: Set up JDK 11
         uses: actions/setup-java@v1
         with:
           java-version: 1.11
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
       - name: Cache SonarCloud packages
         uses: actions/cache@v1
         with:
@@ -39,27 +79,32 @@ jobs:
           New-Item -Path .\.sonar\scanner -ItemType Directory
           dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
 
+          
+      # Build Project
       - name: Restore project
         run: |
           dotnet workload restore
           dotnet restore
 
-      - name: Init SonarCloud Analyzer
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: >
-          .\.sonar\scanner\dotnet-sonarscanner begin
-          /k:"Michaelvsk_GameDb"
-          /o:"github-michaelvsk"
-          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
-          /d:sonar.host.url="https://sonarcloud.io"
+          Write-Host $env:artifact_version
+
+      #- name: Init SonarCloud Analyzer
+      #  env:
+      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #  run: >
+      #    .\.sonar\scanner\dotnet-sonarscanner begin
+      #    /k:"Michaelvsk_GameDb"
+      #    /o:"github-michaelvsk"
+      #    /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+      #    /d:sonar.host.url="https://sonarcloud.io"
+      #    /d:sonar.projectVersion=$env:artifact_version
 
       - name: Build Project
         run: dotnet build -c Release
 
-      - name: Finish SonarCloud Analyzer
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+      #- name: Finish SonarCloud Analyzer
+      #  env:
+      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #  run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
